---
- name: copy tomcat user xml file into side 
  template:
     src: templates/mytomuser.j2
     dest: /opt/tomcat/conf/tomcat-users.xml 

- name: copy tomcat context file inti node 
  template:
     src: templates/mycontext.j2
     dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy tomcat hostcontext file inti node 
  template:
     src: templates/myhostcontext.j2
     dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml